// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mundri_task.Data;

#nullable disable

namespace Mundri_task.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240612040151_seedEmployee")]
    partial class seedEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mundri_task.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Engineering",
                            Name = "John Doe",
                            Salary = 60000
                        },
                        new
                        {
                            Id = 2,
                            Department = "Marketing",
                            Name = "Jane Smith",
                            Salary = 55000
                        },
                        new
                        {
                            Id = 4,
                            Department = "Human Resources",
                            Name = "Bob Brown",
                            Salary = 50000
                        },
                        new
                        {
                            Id = 5,
                            Department = "Sales",
                            Name = "Charlie Davis",
                            Salary = 70000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
